import { StyleSheet, Platform } from "react-native";
import Colors from "../../../constants/Colors";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";
import { RFValue } from "react-native-responsive-fontsize";

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: "#ffffff",
    paddingTop: Platform.OS === "ios" ? 40 : 0,
    paddingBottom: Platform.OS === "ios" ? 0 : 0,
  },
  mainBody: {
    width: "100%",
    height: "80%",
    alignItems: "center",
  },
  flexmain: { width: "90%", alignSelf: "center", alignItems: "center" },
  flexDirectionView: {
    width: "100%",
    flexDirection: "row",
    height: 30,
    borderColor: Colors.black,
    marginBottom: 10,
  },
  titleView: {
    width: "80%",
    justifyContent: "center",
  },
  iconView: {
    width: "20%",
    justifyContent: "center",
    alignItems: "center",
  },
  titleText: {
    fontSize: RFValue(15, 580),
    color: Colors.black,
    fontFamily: "Poppins-SemiBold",
  },
  box: {
    width: 150,
    height: 150,
    marginTop: 25,
    backgroundColor: "#000000",
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    margin: 10,
    paddingHorizontal: wp(2),
  },
  borderedView: {
    width: 150,
    height: 150,
    marginTop: 25,
    backgroundColor: "#000000",
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    margin: 10,
    borderColor: "#ff0000",
    paddingHorizontal: wp(2),
  },
  TextStyle: {
    color: "#fff",
    fontSize: RFValue(12, 580),
    fontFamily: "Poppins-SemiBold",
    textAlign: "center",
    lineHeight: 21,
    letterSpacing: 2,
  },
  inputMainView: {
    width: "90%",
    backgroundColor: Colors.black,
    borderRadius: 8,
    marginTop: "3%",
    marginBottom: "3%",
    justifyContent: "center",
    alignSelf: "center",
    height: Platform.OS === "ios" ? 60 : 60,
  },
  inputTitleView: {
    width: "95%",
    alignSelf: "center",
    height: 20,
    justifyContent: "center",
  },
  inputTitleText: {
    color: Colors.white,
    fontSize: Platform.OS === "ios" ? RFValue(8, 580) : RFValue(10, 580),
    fontFamily: "poppins-regular",
  },
  inputTypeMainView: {
    width: "95%",
    alignSelf: "center",
    borderColor: Colors.white,
    flexDirection: "row",
    height: 40,
  },
  inputTypeView: {
    width: "90%",
    height: 40,
    justifyContent: "center",
  },
  inputTypeStyle: {
    width: "100%",
    height: 40,
    fontSize: RFValue(10, 580),
    fontFamily: "Poppins-Regular",
    color: "#fff",
  },
  centeredView: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  modalView: {
    width: "100%",
    paddingVertical: 20,
    backgroundColor: Colors.white,
    shadowColor: Colors.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 1,
    shadowRadius: 6.84,
    borderWidth: 1,
    borderColor: "lightgrey",
    elevation: 5,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  addText: {
    textAlign: "center",
    fontSize: RFValue(16, 580),
    fontFamily: "Poppins-SemiBold",
    color: "black",
  },
  rowView: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    marginTop: 20,
  },
  mainbtnView: {
    width: "50%",
    alignItems: "center",
    justifyContent: "center",
    borderColor: "#fff",
  },
  ccbtnview: {
    backgroundColor: "#F2F2F2",
    width: 163,
    height: 58,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  profilebtnview: {
    backgroundColor: "#ff0000",
    width: 163,
    height: 58,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  btntextstyle: {
    color: "#ff0000",
    fontSize: RFValue(12, 580),
    fontFamily: "Poppins-Regular",
  },
  btntextstyle1: {
    color: "#fff",
    fontSize: RFValue(12, 580),
    fontFamily: "Poppins-Regular",
  },
});
export default styles;
